const XLSX = require("xlsx");
const fs = require("fs");

const assets = [
	{
		Name: "Precision Lathe X-100",
		"Asset Tag": "AST-MACH-010",
		Type: "movable",
		Category: "Machinery",
		Location: "Workshop Floor 1",
		Manufacturer: "Mazak",
		Model: "Quick Turn 100",
		"Serial Number": "MZ-100293",
		"Purchase Date": "2024-01-15",
		"Purchase Cost": "125000",
		"Warranty Expiry": "2027-01-15",
		Status: "active",
		Description: "High-precision lathe for metalworking",
	},
	{
		Name: "Server Rack Alpha",
		"Asset Tag": "AST-IT-020",
		Type: "immovable",
		Category: "IT Infrastructure",
		Location: "Data Center Room 4",
		Manufacturer: "Dell",
		Model: "PowerEdge R750",
		"Serial Number": "DL-SERV-7501",
		"Purchase Date": "2023-11-10",
		"Purchase Cost": "12000",
		"Warranty Expiry": "2026-11-10",
		Status: "active",
		Description: "Primary database server rack",
	},
	{
		Name: "Electric Forklift",
		"Asset Tag": "AST-LOG-030",
		Type: "movable",
		Category: "Logistics",
		Location: "Warehouse Loading Dock",
		Manufacturer: "Toyota",
		Model: "8FBMT25",
		"Serial Number": "TY-FL-9912",
		"Purchase Date": "2023-05-20",
		"Purchase Cost": "45000",
		"Warranty Expiry": "2026-05-20",
		Status: "active",
		Description: "Electric counterbalanced forklift",
	},
	{
		Name: "Backup Generator 500kW",
		"Asset Tag": "AST-UTIL-040",
		Type: "immovable",
		Category: "Utilities",
		Location: "Exterior - North Side",
		Manufacturer: "Cummins",
		Model: "C500D5P",
		"Serial Number": "CM-GEN-500K",
		"Purchase Date": "2022-08-05",
		"Purchase Cost": "75000",
		"Warranty Expiry": "2027-08-05",
		Status: "active",
		Description: "Emergency backup power system",
	},
	{
		Name: "Industrial 3D Printer",
		"Asset Tag": "AST-RND-050",
		Type: "movable",
		Category: "Research & Development",
		Location: "Lab Room 2",
		Manufacturer: "Stratasys",
		Model: "F370",
		"Serial Number": "SS-3DP-7482",
		"Purchase Date": "2024-02-12",
		"Purchase Cost": "55000",
		"Warranty Expiry": "2026-02-12",
		Status: "active",
		Description: "FDM 3D printer for prototyping",
	},
	{
		Name: "Central AC Chiller",
		"Asset Tag": "AST-HVAC-060",
		Type: "immovable",
		Category: "HVAC",
		Location: "Rooftop - Block A",
		Manufacturer: "Carrier",
		Model: "AquaEdge 19XR",
		"Serial Number": "CR-HVAC-9002",
		"Purchase Date": "2023-03-12",
		"Purchase Cost": "185000",
		"Warranty Expiry": "2028-03-12",
		Status: "active",
		Description: "Main centrifugal chiller for office cooling",
	},
	{
		Name: "CCTV Control Hub",
		"Asset Tag": "AST-SEC-070",
		Type: "movable",
		Category: "Security",
		Location: "Security Control Room",
		Manufacturer: "Hikvision",
		Model: "DS-9664NI-I8",
		"Serial Number": "HK-NVR-5542",
		"Purchase Date": "2023-09-25",
		"Purchase Cost": "3500",
		"Warranty Expiry": "2025-09-25",
		Status: "active",
		Description: "64-channel network video recorder",
	},
	{
		Name: "Smart Board Pro 85",
		"Asset Tag": "AST-OFF-080",
		Type: "movable",
		Category: "Office Equipment",
		Location: "Conference Room 1",
		Manufacturer: "SMART Technologies",
		Model: "SBID-7286R",
		"Serial Number": "ST-SB-8501",
		"Purchase Date": "2024-01-05",
		"Purchase Cost": "8500",
		"Warranty Expiry": "2026-01-05",
		Status: "active",
		Description: "85-inch interactive 4K display",
	},
	{
		Name: "Water Filtration System",
		"Asset Tag": "AST-UTIL-090",
		Type: "immovable",
		Category: "Utilities",
		Location: "Cafeteria - Back Area",
		Manufacturer: "Kent",
		Model: "Elite II",
		"Serial Number": "KT-RO-4421",
		"Purchase Date": "2023-06-18",
		"Purchase Cost": "1200",
		"Warranty Expiry": "2024-06-18",
		Status: "active",
		Description: "Commercial RO water purification system",
	},
	{
		Name: "Heavy Duty Air Compressor",
		"Asset Tag": "AST-MACH-100",
		Type: "movable",
		Category: "Machinery",
		Location: "Workshop Floor 2",
		Manufacturer: "Ingersoll Rand",
		Model: "SS3L3",
		"Serial Number": "IR-AC-1092",
		"Purchase Date": "2023-12-02",
		"Purchase Cost": "2800",
		"Warranty Expiry": "2025-12-02",
		Status: "active",
		Description: "3HP industrial air compressor",
	},
];

// convert JSON → worksheet
const worksheet = XLSX.utils.json_to_sheet(assets);

// create workbook
const workbook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, worksheet, "Assets");

// write file
XLSX.writeFile(workbook, "assets_demo2.xlsx");

console.log("Excel file generated: assets_demo.xlsx");
